ALTER TABLE reviews
    ADD COLUMN stability FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN difficulty FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN reps INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN lapses INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN due TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

DROP TABLE IF EXISTS card_state;
